[monitor://$SPLUNK_HOME/etc/apps/hunt_lab/dataset/fortigate.log]
sourcetype = fortigate
index = hunt_lab
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/hunt_lab/dataset/sysmon.jsonl]
sourcetype = sysmon:json
index = hunt_lab
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/hunt_lab/dataset/windows_security.jsonl]
sourcetype = wineventlog:security:json
index = hunt_lab
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/hunt_lab/dataset/windows_system.jsonl]
sourcetype = wineventlog:system:json
index = hunt_lab
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/hunt_lab/dataset/powershell.jsonl]
sourcetype = powershell:json
index = hunt_lab
disabled = false
